version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:15.10.3-ce.0'
    hostname: "${HOSTNAME}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${HOSTNAME}'
        letsencrypt['contact_emails'] = ['clapp@s
tanford.edu']
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'noreply@${HOSTNAME}'
        gitlab_rails['gitlab_email_display_name'] = 'GitLab'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@${HOSTNAME}'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "mailserver"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_domain'] = '${HOSTNAME}'
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['lfs_object_store_enabled'] = true 
        gitlab_rails['lfs_object_store_remote_directory'] = '${BUCKET}'
        gitlab_rails['lfs_object_store_proxy_download'] = true
        gitlab_rails['lfs_object_store_connection'] = {
            'provider' => 'Google',
            'region'=> "us-central1",
            'google_project' => '${PROJECT}',
            'google_client_email' => '${SERVICE_ACCOUNT}',
            'google_json_key_location' => '/etc/gitlab/key.json'
        }

    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /web/gitlab/etc:/etc/gitlab
      - /web/gitlab/var:/var/log/gitlab
      - /web/gitlab/data:/var/opt/gitlab

  mailserver:
      image: boky/postfix
      container_name: mailserver
      environment:
       ALLOWED_SENDER_DOMAINS: '${HOSTNAME}'
